### ISSUE TITLE
Requires a dedicated server 

### ISSUE THREAD

**Issue by roycol** [guashtiSingh/EatOutEatSafeSoftwareProject#1]
Heavy research is required to find out an affordable and available solution.

Possible solutions
1. MicroSoft Azure
2. Amazon Web Services (AWS)
3. 1and1 
4. Godaddy
5. Rackspace

**Comment by iloy1004** [comment]
Amazon Web Service is the best option for us because they've provided 12 months free account for new user.  I'll create new account, then we can use that.

**Comment by roycol** [comment]
We decided to use the AWS.

**Comment by AnjithBabu** [comment]
Great, if somehow amazon does not work, we can switch to Azure. Sine now we have dreamspark account

**Comment by hlac** [comment]
#2
