### ISSUE TITLE
Set up a dedicated server on AWS(Amazon Web Services)

### ISSUE THREAD

**Issue by roycol** [guashtiSingh/EatOutEatSafeSoftwareProject#2]
After choosing the service provider as AWS, the following tasks are required.
1. Creating an account on AWS
2. Setting up a server as a dedicated server
3. Installing web servers (IIS and Apache Tomcat)
4. Configuring firewall and application rules on both server and AWS
5. Testing connection to web servers

**Comment by iloy1004** [comment]
I did required steps from 1 to 3, creating AWS account, setting and installing web server.
It's done 1 to 3 tasks, so we need working from 4 task.

**Comment by roycol** [comment]
I'll work on it

**Comment by roycol** [comment]
I've completed the configuration of IIS and firewall, but still struggling with tomcat. It seems that there needs an additional permission setting on AWS to access the tomcat server since it uses a different port. (I've already opened the specific port, 8080, but couldn't access to the server.)

**Comment by guashtiSingh** [comment]
I found a link that we could use to try and fix the tomcat server issue that you're having. Please see the link below http://coenraets.org/blog/2011/11/set-up-an-amazon-ec2-instance-with-tomcat-and-mysql-5-minutes-tutorial/

**Comment by hlac** [comment]
Take a look at this and find something similar on Windows: https://forums.aws.amazon.com/message.jspa?messageID=195309

**Comment by AnjithBabu** [comment]
Issue is fixed, the reason was the firewall in the virtual machine (Windows machine where the tomcat was running). 
I have disabled the firewall for now to allow access. We will add some custom rules later

for now I am able to access this URL : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/

**Comment by roycol** [comment]
Great work!! Anjith. I just checked it at home and was able to access tomcat page through 8080 port.

**Comment by hlac** [comment]
#1
