### ISSUE TITLE
Rest API for restaurants list

### ISSUE THREAD

**Issue by iloy1004** [guashtiSingh/EatOutEatSafeSoftwareProject#6]
I've finished rest APIs for restaurants list - categorized by popular, location, allergy and search list.
Below addresses are the link you can call from android.
1. **Default: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant**
   This will be show list of all restaurants in the database
2. **Popular: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant/list/P**
   This will be show list of popular restaurants only higher rate of 6 restaurants
3. **Location: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant/list/L**
   This will be show list of all restaurants group by locations
4. **Allergy: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant/list/A**
   This will be show list of all restaurants group by allergies
5. **Search list: ./restaurant/list/{Keyword whatever user input}**
   **http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant/list/M/pizza**
   This will be show the result of searching by keyword

Please feel free to let me know if you want to change anything.  Then, I'll fix and upload code on repo and our server.

**Comment by iloy1004** [comment]
@AnjithBabu @chemceem Could you give us JSON format example for restaurant's detail page and others if you have some necessary format?

**Comment by AnjithBabu** [comment]
@iloy1004  this is good.  One question , 
what type of request is webservice call GET or POST?

Never mind. Found it. GET

**Comment by AnjithBabu** [comment]
@roycol @iloy1004 
Could you add two more fields in the JSON data. 

{
         "_id": "test",
          "name": "test",
          "image_url": "test",
          "description": "test description 1",
          "rating": 3,
          "reviews": 33
                  "allergy_type": "Milk" // show the type of allergy relates to
                   "location" : "Toronto" //location where the restaurant is 
}

This is required group when showing restaurants based on Allergy and Location

**Comment by iloy1004** [comment]
@AnjithBabu 
do you want that allergy name and location are showed all type of list? popular, allergy and location lists?

**Comment by AnjithBabu** [comment]
@iloy1004  yes please

**Comment by AnjithBabu** [comment]
@roycol @iloy1004 
we need one more webservice in listing section  One which returns a particular restaurant details, based on rest Id.  It should also return the customer reviews regarding that particular restaurant.

Following details are required 
1. Series of res images (like in the website).
2. Comments regarding that restaurant. 
   (Rest of the details we can take from the list like description, name etc.)

This is required to show details when user clicks on a particular restaurant.

**Comment by roycol** [comment]
The web services for a restaurant's details are ready to use. it will return a restaurant's all the details and images in JSON Array. (please refer to a sample below)
- Restaurant detail : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080//EOES-webService/restaurant/resDetail/39958
- result JSON Array of above.
  {
  "resImages":
      [{"Img_Path":"http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com/images/","rowNo":"1","Img_Name":"Almond Butterfly-01.jpg"}
      ,{"Img_Path":"http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com/images/","rowNo":"2","Img_Name":"Almond Butterfly-03.jpg"}
      ,{"Img_Path":"http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com/images/","rowNo":"3","Img_Name":"Almond Butterfly-02.jpg"}]
  ,"resDetails":
      [{"ManagerName":"Manager","Res_Name":"Almond Butterfly","Location_Embed":"<iframe src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2886.2875407305887!2d-79.4056475843055!3d43.662989359815256!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc9175f71d85973%3A0x873731e3af7f7304!2sAlmond+Butterfly!5e0!3m2!1sen!2sca!4v1460344980868' frameborder='0' style='border:0' allowfullscreen><\/iframe>","ResCategory":"Fast Food","Res_Description":"Located in downtown Toronto\u2019s vibrant Harbord Street village, just South of Bloor (two blocks west of Spadina), Almond Butterfly is a 100% gluten-free bake shop and espresso bar. You can find us at 100A Harbord Street. Click here for directions.HOMEMADE, FRESH BAKED GOODS & TREATS From fresh-baked muffins, biscuits, and bagels... to our mouth-watering cupcakes, brownies, & cookies- we\u2019ve got you covered.Toasted breakfast egg sandwiches, bagels (we make the bagels fresh right here every morning), and grilled lunch sandwiches that will definitely hit the spot. In the Annex? Come by the shop to enjoy a scrumptious, grilled turkey & pesto sandwich... or perhaps a melt-in-your-mouth ham & cheddar melt, hot off the grill? All gluten-free, of course. :) DINE-IN, TAKEOUT, OR DELIVERY!","Province":"Ontario","LocationName":"Toronto"}]

}

**Comment by roycol** [comment]
In order to get comments, we have another web service. it's because we separate classes for web services based on C# classes to avoid any confusion. (however, if required, we will consider to combine them into a web service. let's talk about it later.)
- top reviews (39958 = res_id) : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/review/list/39958  

as a default, result of above will return top review list only.
You can add 1 or 0 at the end of the address to specify a type of the reviews. (1:top reviews only, 0:all reviews)
- all reviews : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/review/list/39958/0

**Comment by roycol** [comment]
as Anjith requested, I've created a webservice to include allergy types(AC_Name) and location(LC_Name). You can invoke it with "M" keyword followed by "/list". so it will look like the examples below.
- http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant/list/M
- (+ search keyword as "pizza") : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/restaurant/list/M/pizza

**Comment by roycol** [comment]
As for the Menu list, please refer to below.
- (restaurant Id= 33958) : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/menu/list/39958
- (+ flag = 1: special menu only, 0: all menus) : http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/menu/list/39958/0

**Comment by AnjithBabu** [comment]
Thanks @roycol , but next time when you guys change the existing JSON attribute that is already published,  for example: restaurant list , please let me know. 

Because I see there is a change in "MainImg_Path" attribute, earlier it was just "/images", but now it is as below.

"MainImg_Path":"http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com/images/"

This was causing error, because I coded based on the previous one and it took me some time to figure it out.  :)

**Comment by roycol** [comment]
Sorry for the inconvenience, Anjith. 
I can roll it back if you don't need the full path of the image. please let me know if you want to have previous image path.

**Comment by roycol** [comment]
I'm closing this issue as we completed both web services for restaurants list and relevant mobile development.

**Comment by roycol** [comment]
I'm closing this issue as we completed both web services for restaurants list and relevant mobile development.

**Comment by AnjithBabu** [comment]
@roycol @iloy1004  , the json of res list got change again.

Image path in latest json got changed . 

Old json : [{"**Img_Path**":"http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com/images/","rowNo":"1","Img_Name":"Almond Butterfly-01.jpg"}

New json i am getting : "**MainImg_Path**":"\/images", 

even the name of variable got changed? Please change the json to agreed format below.

[{"**Img_Path**":"http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com/images/"

**Comment by roycol** [comment]
Sorry for the inconvenience. 
I've modified it to the agreed format.
please check it again

**Comment by AnjithBabu** [comment]
Yes, now it is working Roy. Thank you.

"MainImg_Path":"http:\/\/ec2-54-218-26-177.us-west-2.compute.amazonaws.com\/images\/",
"MainImg_Name":"almond.jpg",

**Comment by AnjithBabu** [comment]
Closing the issue
