### ISSUE TITLE
Rest API for user service

### ISSUE THREAD

**Issue by roycol** [guashtiSingh/EatOutEatSafeSoftwareProject#7]
UserService will provide the authentication and the registration functionality.

In order to implement a web service for **signup**, there will be 2 possible ways considered to get user details from mobile.

1. GET with **key=value**
2. POST with **json**

Please let me know your preference.

**Comment by roycol** [comment]
As we discussed, I've created the user service based on #2(POST with JSON). 
Please refer to below for the details.

1. login

- URL: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/user/login
- input type: JSON - **be careful with names. it's case sensitive.**  
 e.g. {"userId": "test", "password": "1234"}
- return type: JSON 
 e.g.1. **when login successed**: 
{"resultMsg":"success", "user":[{"User_FirstName":"Jihee","User_LastName":"Seo", "User_Email":"iloy1004ca@gmail.com","UC_Id":"2"}]}
 e.g.2 **when failed**: {"resultMsg":"fail","user":""})

2. signup

- URL: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/user/signup
- input type: JSON - **be careful with names. it's case sensitive.** 
e.g. {"userId":"test9999","password":"1234","firstName":"mm","lastName":"ll","email":"aa@aa.aa"}
- return type: JSON
e.g.1. **when signup successed**: {"resultMsg":"success"}
e.g.2 **when failed**: {"resultMsg":"fail"}

**Comment by AnjithBabu** [comment]
perfect Roy, I have created the login form. I have created the login without the web service call now I will integrate it soon and let you know.

**Comment by AnjithBabu** [comment]
The inital commit for Login Functionality has been committed to Mobile Branch. @iloy1004  Jihee  you can pull that and work. I will reply if any doubts on Monday.

**Comment by iloy1004** [comment]
@AnjithBabu I've started developing review part in restaurant detail view.  so, please let me know if you have any other changes in that page, then I'll reflect your changes to my work.

**Comment by AnjithBabu** [comment]
Thanks @iloy1004 . 

I have finished login , now even if you go back to previous activity after singn out , the session will be invalid. Earlier it was still showing as the user logged in. 

Also I am almost done with Signup I will commit it tomorrow.

**Comment by AnjithBabu** [comment]
The Singup and login functionalities have been done and completed. Committed code to the Mobile branch. 
Closing the issue.
