### ISSUE TITLE
Rest API for review service

### ISSUE THREAD

**Issue by roycol** [guashtiSingh/EatOutEatSafeSoftwareProject#8]
I've created a web service for manipulating review. please refer to below for details.

1. **review list**: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/review/list/39958/1
e.g. restaurantId = 33958, isTopReviews = 1 // 0: all, 1: top reivews only

2. **insert a review**
- URL: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/review/insert
- input type: JSON - be careful with names. it's case sensitive.
e.g. {"resId":"39958","reviewTitle":"good restaurant!!","reviewContent":"this restaurant is good","userId":"test","mainImgPath":"","mainImgName":"","rate":"5"}
- return type: JSON
e.g.1. when successed: {"resultMsg":"success"}
e.g.2 when failed: {"resultMsg":"fail"}

3. **update a review**
- URL: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/review/update
- input type: JSON - be careful with names. it's case sensitive.
e.g. {"resId":"39958","reviewId":"34525690","reviewTitle":"good restaurant!!","reviewContent":"this restaurant is good","userId":"test","mainImgPath":"","mainImgName":"","rate":"5"}
- return type: JSON
e.g.1. when successed: {"resultMsg":"success"}
e.g.2 when failed: {"resultMsg":"fail"}

4. **delete a review**
- URL: http://ec2-54-218-26-177.us-west-2.compute.amazonaws.com:8080/EOES-webService/review/delete
- input type: JSON - be careful with names. it's case sensitive.
e.g. {"reviewId":"34525690","userId":"test"}
- return type: JSON
e.g.1. when successed: {"resultMsg":"success"}
e.g.2 when failed: {"resultMsg":"fail"}

**Comment by iloy1004** [comment]
@roycol Thank you, Roy! I'm done review list, and working on review CUD now.  Will upload it after everything is done.

**Comment by AnjithBabu** [comment]
Thanks for uploading the review list part @iloy1004 . I have made some changes to the review to show the list. I will commit it soon.

**Comment by AnjithBabu** [comment]
Committed the changes

**Comment by iloy1004** [comment]
@AnjithBabu I finished review functions, updating and deleting.  Completed to commit files via Mobile branch , so please check it.

**Comment by AnjithBabu** [comment]
It is working as expected @iloy1004 . Thank you. 

Closing the issue
